# Generated by Django 2.1.5 on 2019-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190225_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
