# Generated by Django 2.1.4 on 2019-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i1c', models.BooleanField(default=False)),
                ('q1c', models.IntegerField(default=1)),
                ('i2c', models.BooleanField(default=False)),
                ('q2c', models.IntegerField(default=1)),
                ('i3c', models.BooleanField(default=False)),
                ('q3c', models.IntegerField(default=1)),
                ('i4c', models.BooleanField(default=False)),
                ('q4c', models.IntegerField(default=1)),
                ('i5c', models.BooleanField(default=False)),
                ('q5c', models.IntegerField(default=1)),
                ('i6c', models.BooleanField(default=False)),
                ('q6c', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('Name', models.TextField(primary_key=True, serialize=False)),
                ('Cost', models.IntegerField()),
            ],
        ),
    ]
