# Generated by Django 2.1.4 on 2019-03-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cost',
        ),
        migrations.AlterField(
            model_name='cart',
            name='i1c',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='i2c',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='i3c',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='i4c',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='i5c',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='i6c',
            field=models.TextField(default=False),
        ),
    ]
