# Generated by Django 2.1.5 on 2019-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcards',
            name='password',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
