# Generated by Django 2.1.5 on 2019-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190311_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='cvv',
            field=models.TextField(default='', null=True),
        ),
    ]
