# Generated by Django 2.1.5 on 2019-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190311_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='amount',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
