# Generated by Django 2.1.5 on 2019-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190311_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcards',
            name='password',
            field=models.CharField(default='2606', max_length=15, null=True),
        ),
    ]
